{
   "swagger":"2.0",
   "info":{
      "version":"1.0.0",
      "title":"Common APIs",
      "description":"All APIs related to the common controller",
      "termsOfService":"#"
   },
   "basePath":"/",
   "tags":[
      {
         "name":"Common",
         "description":"API for common usage"
      }
   ],
   "schemes":[
      "https",
      "http"
   ],
   "consumes":[
      "application/json"
   ],
   "produces":[
      "application/json"
   ],
   "paths":{
      "/common/countries":{
         "get":{
            "tags":[
               "Common"
            ],
            "description":"How to get countries",
            "operationId":"for the URL",
            "produces":[
               "application/json"
            ],
            "parameters":[
                             
            ],
            "responses":{
               "200":{
                  "description":"Countries Found!",
                  "schema":{
                      "$ref":"#/definitions/countryresponse"
                  }
               },
               "400":{
                  "description":"Page not found",
                  "schema":{
                     "$ref":"#/definitions/400error"
                  }
               }               
            }
         }
      },
      "/common/province/{country_id}":{
         "get":{
            "tags":[
               "Common"
            ],
            "description":"Get country specific province by using country_id",
            "operationId":"province",
            "produces":[
               "application/json"
            ],
            "parameters":[
               {
                  "name":"country_id",
                  "in":"path",
                  "description":"Country ID",
                  "required":true,
                  "type":"string"
               }             
            ],
            "responses":{
               "200":{
                  "description":"province response",
                  "schema":{
                     "$ref":"#/definitions/provinceresponse"
                  }
               },
               "400":{
                  "description":"Page not found",
                  "schema":{
                     "$ref":"#/definitions/400error"
                  }
               } 
            }
         }
      },
      "/common/allprovince":{
         "get":{
            "tags":[
               "Common"
            ],
            "description":"Get all province",
            "operationId":"get",
            "produces":[
               "application/json"
            ],
            "parameters":[
            ],
            "responses":{
               "200":{
                  "description":"province response",
                  "schema":{
                     "$ref":"#/definitions/allprovinceresponse"
                  }
               },
               "400":{
                  "description":"Page not found",
                  "schema":{
                     "$ref":"#/definitions/400error"
                  }
               } 
            }
         }
      },
      "/common/countrieslist/{limit}":{
         "get":{
            "tags":[
               "Common"
            ],
            "description":"Get all countries list for (shop by countries and countries list page)",
            "operationId":"countrieslist",
            "produces":[
               "application/json"
            ],
            "parameters":[
               {
                  "name":"limit",
                  "in":"path",
                  "description":"No of records to get.",
                  "required":true,
                  "type": "integer"
               }               
            ],
            "responses":{
               "200":{
                  "description":"Countries found",
                  "schema":{
                     "$ref":"#/definitions/countriesList"
                  }
               },
               "404":{
                  "description":"Failed to get Countries",
                  "schema":{
                     "$ref":"#/definitions/404countriesList"
                  }
               },
               "500":{
                  "description":"Unable to process request",
                  "schema":{
                     "$ref":"#/definitions/500countriesList"
                  }
               }               
            }
         }
      },
      "/common/countrylanguage/{langauge_code}":{
         "get":{
            "tags":[
               "Common"
            ],
            "description":"Get all content related to country language using (langauge_code) example en,fr, etc.",
            "operationId":"countrylanguage",
            "produces":[
               "application/json"
            ],
            "parameters":[
               {
                     "name":"langauge_code",
                     "in":"path",
                     "description":"Site language id",
                     "required":true,
                     "type":"integer"
               } 
            ],
            "responses":{
               "200":{
                  "description":"top countries response",
                  "schema":{
                     "$ref":"#/definitions/countrieslanguage"
                  }
               },
               "400":{
                  "description":"Page not found",
                  "schema":{
                     "$ref":"#/definitions/400error"
                  }
               } 
            }
         }
      },
      "/common/page/{langauge_code}/{slug}":{
         "get":{
            "tags":[
               "Common"
            ],
            "description":"Get all content related to country language using (langauge_code) example en,fr, etc.",
            "operationId":"countrylanguage",
            "produces":[
               "application/json"
            ],
            "parameters":[
               {
                  "name":"langauge_code",
                  "in":"path",
                  "description":"Site language id",
                  "required":true,
                  "type":"integer"
               },
               {
                  "name":"slug",
                  "in":"path",
                  "description":"Page slug",
                  "required":true,
                  "type":"string"
               }                 
            ],
            "responses":{
               "200":{
                  "description":"Record found",
                  "schema":{
                     "$ref":"#/definitions/200page"
                  }
               },
               "404":{
                  "description":"Page not found",
                  "schema":{
                     "$ref":"#/definitions/404page"
                  }
               },
               "500":{
                  "description":"Unable to process request, Please try again!",
                  "schema":{
                     "$ref":"#/definitions/500page"
                  }
               }
            }
         }
      },
      "/common/header":{
         "get":{
            "tags":[
               "Common"
            ],
            "description":"Header Page API (Countries and Provinces, Language, Currency, Language Translation Content)",
            "operationId":"header",
            "produces":[
               "application/json"
            ],
            "parameters":[
               {
                  "name":"token",
                  "in":"header",
                  "description":"Logged in customer token.",
                  "required":false,
                  "type":"string"
               },
               {
                  "name":"cart_key",
                  "in":"header",
                  "description":"Cart key.",
                  "required":false,
                  "type":"string"
               },               
               {
                  "name":"langauge_code",
                  "in":"query",
                  "description":"Site language id.",
                  "required":false,
                  "type":"integer"
               },
               {
                  "name":"country_shortcode",
                  "in":"query",
                  "description":"country shortcode",
                  "required":false,
                  "type":"string"
               },
               {
                  "name":"country_slug",
                  "in":"query",
                  "description":"country slug",
                  "required":false,
                  "type":"string"
               }                                
            ],
            "responses":{
               "200":{
                  "description":"Record found",
                  "schema":{
                     "$ref":"#/definitions/200header"
                  }
               },
               "500":{
                  "description":"Unable to process request, Please try again!",
                  "schema":{
                     "$ref":"#/definitions/500header"
                  }
               }
            }
         }
      }      
   },
   "definitions":{
      "create":{
         "properties":{
            "eventId":{
               "required":true,
               "type":"string",
               "example":"mathmaticial"
            },
            "numberRequired":{
               "required":true,
               "type":"integer",
               "format":"int64",
               "example":500
            }
         }
      },
      "response1":{
         "properties":{
            "jobID":{
               "required":true,
               "type":"string",
               "example":"23423456543"
            },
            "request":{
               "required":true,
               "type":"schema",
               "example":{
                  "eventId":"mathmaticial",
                  "numberRequired":500
               }
            }
         }
      },
      "countryresponse":{
         "properties":{
            "status":{
               "type":"boolean",
               "example":"true"
            },
            "code":{
               "type":"integer",
               "example":"200"
            },            
            "message":{
               "type":"string",
               "example":"Countries found"
            },
            "result":{
               "type":"object",
               "example":[
                  {
                     "id": 5,
                     "continet_name": 5,
                     "country_domain": "http://18f.mobikasa.com/",
                     "country_name": "Australia",
                     "preferred_currency_id": 6,
                     "country_alias": "",
                     "short_code": "AU",
                     "iso_code": "AUS",
                     "zipcode_length": 5,
                     "zipcode_type": 1,
                     "calling_code": "61",
                     "show_state": 0,
                     "required_zipcode": "0",
                     "country_flag": "26-10-2015+06-38-30australia.jpg",
                     "company_logo": "26-10-2015+06-38-30australia.jpg",
                     "surcharge": 0,
                     "phone": "1-800-858-5140",
                     "is_display": 1,
                     "status": 1,
                     "redirect_url": "http://1800flowers.ca"
                   }                  
               ]
            }
         }
      },
      "provinceresponse":{
         "properties":{
            "status":{
               "type":"boolean",
               "example":"true"
            },
            "code":{
               "type":"integer",
               "example":"200"
            },            
            "message":{
               "type":"string",
               "example":"Provinces found"
            },
            "result":{
               "type":"object",
               "example":[
                  {
                     "id": 4,
                     "province_name": "New York"
                   }
               ]
            }
         }
      },
      "allprovinceresponse":{
         "properties":{
            "status":{
               "type":"boolean",
               "example":"true"
            },
            "code":{
               "type":"integer",
               "example":"200"
            },            
            "message":{
               "type":"string",
               "example":"Provinces found"
            },
            "result":{
               "type":"object",
               "example":[
                  {
                     "id": 4,
                     "country_name": "United States"
                   }
               ]
            }
         }
      },
      "countriesList":{
         "properties":{
            "status":{
               "type":"boolean",
               "example": "true"
            },
            "code":{
               "type":"integer",
               "example":"200"
            },            
            "message":{
               "type":"string",
               "example":"Countries found"
            },
            "result":{
               "type":"object",
               "example":[
                  {
                     "country_name": "Canada",
                     "is_display": 0,
                     "country_flag": "17-10-2015+14-12-24canada.jpg",
                     "phone": "1-800-858-5039",
                     "redirect_url": "",
                     "country_domain": "http://18f.mobikasa.com/"
                   },
                   {
                     "country_name": "Australia",
                     "is_display": 1,
                     "country_flag": "26-10-2015+06-38-30australia.jpg",
                     "phone": "1-800-858-5140",
                     "redirect_url": "http://1800flowers.ca",
                     "country_domain": "http://18f.mobikasa.com/"
                   }
               ]
            }
         }
      },
      "404countriesList":{
         "properties":{
            "status":{
               "type":"boolean",
               "example":"false"
            },
            "code":{
               "type":"integer",
               "example":"404"
            },            
            "message":{
               "type":"string",
               "example":"Failed to get Countries"
            }
         }
      },
      "500countriesList":{
         "properties":{
            "status":{
               "type":"boolean",
               "example":"false"
            },
            "code":{
               "type":"integer",
               "example":"500"
            },            
            "message":{
               "type":"string",
               "example":"Unable to process request"
            }
         }
      },
      "countrieslanguage":{
         "properties":{
            "status":{
               "type":"boolean",
               "example":"true"
            },
            "code":{
               "type":"integer",
               "example":"200"
            },            
            "message":{
               "type":"string",
               "example":"Countries language content found"
            },
            "result":{
               "type":"object",
               "example":[
                  {
                     "key": "submit",
                     "translated_text": "Submit"
                   }
               ]
            }
         }
      },
      "400error":{
         "properties":{
            "status":{
               "type":"boolean",
               "example":"False"
            },
            "code":{
               "type":"integer",
               "example":"400"
            },                        
            "message":{
               "type":"string",
               "example":"400 Bad Request"
            }
         }
      },
      "200page":{
         "properties":{
            "status":{
               "type":"boolean",
               "example": "true"
            },
            "code":{
               "type":"integer",
               "example":"200"
            },            
            "message":{
               "type":"string",
               "example":"Record found"
            },
            "result":{
               "type":"object",
               "example":[
                  {
                     "id": 16,
                     "page_name": "Contact Us",
                     "slug": "contact-us",
                     "page_title": "Contact Us",
                     "placement": 1
                  }                  
               ]
            }
         }
      },
      "404page":{
         "properties":{
            "status":{
               "type":"boolean",
               "example":"false"
            },
            "code":{
               "type":"integer",
               "example":"404"
            },            
            "message":{
               "type":"string",
               "example":"Page not found"
            }
         }
      },
      "500page":{
         "properties":{
            "status":{
               "type":"boolean",
               "example":"false"
            },
            "code":{
               "type":"integer",
               "example":"500"
            },            
            "message":{
               "type":"string",
               "example":"Unable to process request, Please try again!"
            }
         }
      },
      "200header":{
         "properties":{
            "status":{
               "type":"boolean",
               "example": "true"
            },
            "code":{
               "type":"integer",
               "example":"200"
            },            
            "message":{
               "type":"string",
               "example":"Record found"
            },
            "result":{
               "type":"object",
               "example":{}
            }
         }
      },
      "500header":{
         "properties":{
            "status":{
               "type":"boolean",
               "example":"false"
            },
            "code":{
               "type":"integer",
               "example":"500"
            },            
            "message":{
               "type":"string",
               "example":"Unable to process request, Please try again!"
            }
         }
      }      
   }
}
